### PR TITLE
[IOTDB-1084] [To rel/0.11] Fix temporary memory of flushing may cause OOM

### PR DESCRIPTION
**Pull request by HTHou**
<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [x] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by asdf2014** [comment]
Hi, @HTHou . Maybe we can use the [Mergify](https://github.com/marketplace/mergify) robot to create these PRs automatically.  This is an example for it in CrateDB: [https://github.com/crate/crate/blob/master/.mergify.yml#L17](https://github.com/crate/crate/blob/master/.mergify.yml#L17). In addition, [a discussion](https://lists.apache.org/thread.html/red60972556aaf20975575207fa2085dfafbfd92cb4b76b64d2340c01%40%3Cdev.iotdb.apache.org%3E) has been initiated in the mail group, welcome to leave comments.

cc @jixuan1989 @qiaojialin

**Comment by HTHou** [comment]
> Hi, @HTHou . Maybe we can use the [Mergify](https://github.com/marketplace/mergify) robot to create these PRs automatically. This is an example for it in CrateDB: https://github.com/crate/crate/blob/master/.mergify.yml#L17. In addition, [a discussion](https://lists.apache.org/thread.html/red60972556aaf20975575207fa2085dfafbfd92cb4b76b64d2340c01%40%3Cdev.iotdb.apache.org%3E) has been initiated in the mail group, welcome to leave comments.

Hi, I do think that's a great idea to use a robot! 
Since we are going to release a bug-fix version of 0.11 right now, I think we can start to use some robots after the 0.11.2 released.

**Comment by asdf2014** [comment]
Hi, @HTHou . Thank you for your comments. Sure, release is the top priority.

**Review by SilverNarcissus — APPROVED** [review]
Look good to me~

**Review by JackieTien97 — APPROVED** [review]

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
