### PR TITLE
IOTDB-1112 some error occurs occasionally in the test case

### PR DESCRIPTION
**Pull request by wangchao316**
## Description

If test cases are run in parallel, a test case class uses the tool class TsFileGeneratorForTest.java to generate a data file. After the execution is complete, the file is deleted. However, another test class is running and the tool class TsFileGeneratorForTest is used to generate a the same name file. As a result, the file cannot be found.

This pr is used to generate different data files for different test case classes and allow them to be executed concurrently in parallel. two test case class be no influence between each other.
This is one of the features of the test case, that is independence.
This problem does not occur in Github because the current Github pr test uses a single thread to execute test cases one by one.

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by jixuan1989** [comment]
Could you describe the intention of the PR first?

**Comment by wangchao316** [comment]
> Could you describe the intention of the PR first?

If test cases are run in parallel, a test case class uses the tool class TsFileGeneratorForTest.java to generate a data file. After the execution is complete, the file is deleted. However, another test class is running and the tool class TsFileGeneratorForTest is used to generate a the same name file. As a result, the file cannot be found.
1. This pr is used to generate different data files for different test case classes and allow them to be executed concurrently in parallel.
2. This is one of the features of the test case, that is independence.
3. This problem does not occur in Github because the current Github pr test uses a single thread to execute test cases one by one.

**Comment by wangchao316** [comment]
@jixuan1989 @qiaojialin  hello , could you please review again? I add explanation

**Comment by jixuan1989** [comment]
I am very interested in how to run tests in parallel.

**Comment by wangchao316** [comment]
> I am very interested in how to run tests in parallel.

we could use TestNG in OpenSource softeware. 

I use my company private parallel-plug-in for iotdb in my local environment now.  

I find that it takes 20 minutes to build Maven in github, but 10 minutes to build and run tests in parallel in my local.
As the number of test cases increases, the execution time increases.
I recommend ：
1.modifying the test cases to be executed in parallel first.
2. and then switch to the parallel framework.

At the same time， if a single thread to execute test cases one by one,  failed to delete data file after a test finished, in this case, an error is reported when following test cases create the same name file .

**Comment by wangchao316** [comment]
@HTHou @jt2594838 @neuyilan  hello , could you review this?
Thanks.

**Comment by jixuan1989** [comment]
> we could use TestNG in OpenSource softeware.

TestNG is more powerful. 
Do you have plan to change current JUnit to TestNG? If not, I wonder the benefit that modifying current test codes.

> I use my company private parallel-plug-in for iotdb in my local environment now.

I am quite interested in parallel test. I know Maven 3 support parallel compiler by using `-T <number>`, but I do not know whether it runs all tests in parallel. 

In conclusion, the point is, what benefit the public repo will get from this PR? (No benefit does not means the pr can not be merged, as we welcome PRs that will making the project easier to be used in users' environment.)

**Comment by wangchao316** [comment]
> get

yes, I plan to change TestNG..

**Pull request closed without merging**
