### PR TITLE
Generate an file COMMITID to store the current commit id when compile distribution

### PR DESCRIPTION
**Pull request by xiaoyekanren**

### CODE REVIEW

**Comment by xiaoyekanren** [comment]
image

**Comment by xiaoyekanren** [comment]
**When download zip in github website without .git, error will be reported and compilation will continue.**  
image

**Comment by ericpai** [comment]
Hey, there's another solution that using a native maven plugin to generate git.properties file, and read the commit hash directly to the process.

server/pom.xml
```xml
<plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.9.10</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                    <includeOnlyProperties>
                        <includeOnlyProperty>^git.commit.id.abbrev$</includeOnlyProperty>
                        <includeOnlyProperty>^git.dirty$</includeOnlyProperty>
                    </includeOnlyProperties>
                    <commitIdGenerationMode>full</commitIdGenerationMode>
                    <failOnNoGitDirectory>false</failOnNoGitDirectory>
                    <offline>true</offline>
                    <gitDescribe>
                        <dirty>-dev</dirty>
                    </gitDescribe>
                </configuration>
            </plugin>
```

IoTDBConstant.java

```java
static {
    Properties prop = new Properties();
    String finalBuildInfo = "UNKNOWN";
    try {
      prop.load(IoTDBConstant.class.getResourceAsStream("/git.properties"));
      finalBuildInfo = prop.getProperty("git.commit.id.abbrev", "UNKNOWN");
      String isDirty = prop.getProperty("git.dirty", "false");
      if (isDirty.equalsIgnoreCase("true")) {
        finalBuildInfo += "-dev";
      }
    } catch (Exception e) {
      System.err.println("get git.properties error: " + e.getMessage());
    }
    BUILD_INFO = finalBuildInfo;
  }

  public static final String BUILD_INFO;
  public static final String VERSION_WITH_BUILD = VERSION + " (Build: " + BUILD_INFO + ")";
```

Then we can not only find the commit info in the dir but also in the iotdb-cli.

**Comment by HTHou** [comment]
@ericpai Good idea! Would you like to submit a PR with your solution?

**Comment by ericpai** [comment]
> @ericpai Good idea! Would you like to submit a PR with your solution?

PTAL this https://github.com/apache/iotdb/pull/7365

**Pull request closed without merging**
