### PR TITLE
[IOTDB-4993] Rename the storage group of permissions to database

### PR DESCRIPTION
**Pull request by RYH61**
add privileges : CREATE_DATABASE | DELETE_DATABASE

### CODE REVIEW

**Comment by RYH61** [comment]
@qiaojialin @SpriCoder Hi, Please review!

**Comment by SpriCoder** [comment]
@qiaojialin Please take a look whether we need to maintain `SET_STORAGE_GROUP | DELETE_STORAGE_GROUP|CREATE_DATABASE | DELETE_DATABASE` at the same time for compatibility.

**Comment by qiaojialin** [comment]
Currently, sg  = database, so we need to maintain both

**Comment by RYH61** [comment]
@qiaojialin @SpriCoder Please take a look at this pr

**Review by SpriCoder — APPROVED** [review]
LGTM. Maybe can reserve some test of set storage group and delete storage group~

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
