### PR TITLE
[Distributed] Make cluster configuration consensus with the single-node

### PR DESCRIPTION
**Pull request by jixuan1989**
I remove iotdb-engines.properties in cluster/src/assemby,
one more issue left:

`thrift_init_buffer_size=1024` is not used.

### CODE REVIEW

**Review by neuyilan — COMMENTED** [review]
I think we can reserve the `thrift_init_buffer_size` parameter, as this is mainly used for the initial thrift frame buffer size, which should be used in the `org.apache.iotdb.rpc.RpcUtils`, I think this parameter is missed when developing this codes. 

besides, those code smells are better to solve

**Review by neuyilan — CHANGES_REQUESTED** [review]
besides, those code smells are better to solve

**Review by mychaow — APPROVED** [review]
LGTM

**Comment by jixuan1989** [comment]
> I think we can reserve the `thrift_init_buffer_size` parameter, as this is mainly used for the initial thrift frame buffer size, which should be used in the `org.apache.iotdb.rpc.RpcUtils`, I think this parameter is missed when developing this codes.

But currently there is no any function calling the parameter..

**Comment by jt2594838** [comment]
That one is free to remove, as it makes little difference especially in long runs, and the default values should be enough.

**Pull request merged**
