### PR TITLE
Fix IT framework

### PR DESCRIPTION
**Pull request by cornmonster**
1. disable Influx DB RPC service to avoid port conflict

### CODE REVIEW

**Review by HTHou — APPROVED** [review]
LGTM

**Review by neuyilan — CHANGES_REQUESTED** [review]
This pr LGTM but whether it is necessary to enable `enable_influxdb_rpc_service=true` as default value in `iotdb-engine.properties`?

**Comment by SteveYurongSu** [comment]
> This pr LGTM but whether it is necessary to enable `enable_influxdb_rpc_service=true` as default value in `iotdb-engine.properties`?

Thanks for pointing this out. @neuyilan  

After the development of the InfluxDB adapter is completed, the parameter `enable_influxdb_rpc_service` will be set to `false` by default. We now set this parameter to true just to make it easier to test using the pipeline. @jun0315

**Comment by neuyilan** [comment]
> We now set this parameter to true just to make it easier to test using the pipeline
OK, got it, thanks.

**Pull request merged**
