### PR TITLE
[IOTDB-1348] Last plan not work in cluster mode

### PR DESCRIPTION
**Pull request by irvine0109**
Last plan not work in cluster mode, and I think `timeValuePairs.get(i).right` also should be judged as not null.

[jira link](https://issues.apache.org/jira/browse/IOTDB-1348)

### CODE REVIEW

**Comment by jixuan1989** [comment]
Hi, strongly suggest to add test in testcontainer module.

**Comment by irvine0109** [comment]
> Hi, strongly suggest to add test in testcontainer module.

Done.

**Review by mychaow — APPROVED** [review]
LGTM

**Review by LebronAl — APPROVED** [review]
LGTM
please execute `mvn spotless:apply` to resolve format issues~

**Comment by mychaow** [comment]
Hi，could you please cherry-pick the pr to rel/0.12.

**Pull request merged**
