### PR TITLE
[IOTDB-1057] Remove Data type ALL in create time series sentence

### PR DESCRIPTION
**Pull request by yuqi1129**
https://issues.apache.org/jira/browse/IOTDB-1057

### CODE REVIEW

**Review by qiaojialin — APPROVED** [review]

**Comment by Genius-pig** [comment]
Keyword `ALL` is used for `group by fill`. I think we should remove ALL in datatype
```
typeClause
    : (dataType | ALL) LS_BRACKET linearClause RS_BRACKET
    | (dataType | ALL) LS_BRACKET previousClause RS_BRACKET
    | (dataType | ALL) LS_BRACKET previousUntilLastClause RS_BRACKET
    ;
```

**Comment by yuqi1129** [comment]
> Keyword `ALL` is used for `group by fill`. I think we should remove `ALL` in datatype, add it in `typeClause`.
> 
> ```
> typeClause
>     : (dataType | ALL) LS_BRACKET linearClause RS_BRACKET
>     | (dataType | ALL) LS_BRACKET previousClause RS_BRACKET
>     | (dataType | ALL) LS_BRACKET previousUntilLastClause RS_BRACKET
>     ;
> ```

DataType is used in other place, I'm not sure whether `ALL` is valid or not in this syntax, no body report `ALL` error in nodeNameWithoutStar the  
`nodeNameWithoutStar
    : ID
    | DOUBLE_QUOTE_STRING_LITERAL
    | DURATION
    | encoding
    | dataType
    | dateExpression
    | MINUS? EXPONENT
    | MINUS? INT
    | booleanClause
    | CREA
`

So, i just change data type definition in create time series grammar

**Comment by qiaojialin** [comment]
Hi, this PR is an optimization of the current definition. 
Indeed the 'ALL' only used in the fill clause, which specifies a fill function for all datatypes. You could have a try :)

**Comment by yuqi1129** [comment]
@qiaojialin @Genius-pig 
Thanks for your clarification, i will take a try and change the PR latter

**Review by qiaojialin — APPROVED** [review]

**Review by JackieTien97 — APPROVED** [review]

**Pull request merged**
