### PR TITLE
[IOTDB-1283] add-node.sh supports printgc

### PR DESCRIPTION
**Pull request by jamber001**
[IOTDB-1283] add-node.sh supports printgc

### CODE REVIEW

**Comment by jamber001** [comment]
@jixuan1989 
Could you help merg PR?

**Review by neuyilan — APPROVED** [review]
LGTM

**Review by mychaow — APPROVED** [review]
LGTM

**Comment by LebronAl** [comment]
Hi, could you please add printgc for add-node.bat in next PR?

**Comment by jamber001** [comment]
> Hi, could you please add printgc for add-node.bat in next PR?

I am not familar with .bat file and have no testing evn too.  I will check whether I can fix it.

**Pull request merged**
