### PR TITLE
Add TsFile Vis Tool

### PR DESCRIPTION
**Pull request by LeiRui**
## Description
Add TsFile Vis Tool. README see "Format.md" Chapter 3.5 Vis Tool.
Plot result example: b1

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by LeiRui** [comment]
I am mofiy Formt.md. So don't review this pr now.

**Comment by LeiRui** [comment]
Welcome review~

**Comment by LeiRui** [comment]
As you will see the changes in "Format.md", I add README for vis tool, and I also rearrange the content structure of this doc to make it more reading friendly.

**Comment by liutaohua** [comment]
Why only commit to 0.11 branch

**Comment by LeiRui** [comment]
> Why only commit to 0.11 branch

Because tsfile structure changed.

**Comment by LeiRui** [comment]
> Why only commit to 0.11 branch

It is left as future work to commit to rel/0.12.

**Comment by LeiRui** [comment]
I'll try to adapt it to rel/0.12 today.

**Review by HTHou — APPROVED** [review]

**Pull request merged**
