### PR TITLE
Refactor the todf() function of client-py to improve performance

### PR DESCRIPTION
**Pull request by fuwei3140**
## Description
Optimized the processing logic of the todf() function in client_py to read the byte stream by column to avoid performance problems caused by reading by row.

<hr>

This PR has:
- [x] been self-reviewed.
    - [x] concurrent read
    - [x] concurrent write
    - [x] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
Thanks for pinging me @SteveYurongSu . The code looks so far fine for me. What wee are generally missing in our python module are tests (we effectively have none). So I really would appreciate any test (based on pytest) to be added to the repo. What do you think @fuwei3140 ?

**Comment by fuwei3140** [comment]
> Thanks for pinging me @SteveYurongSu . The code looks so far fine for me. What wee are generally missing in our python module are tests (we effectively have none). So I really would appreciate any test (based on pytest) to be added to the repo. What do you think @fuwei3140 ?

**Comment by fuwei3140** [comment]
This is a good proposal, and a complete test is necessary @JulianFeinauer . I can try to use pytest to implement tests on various data type queries. @SteveYurongSu

**Comment by SteveYurongSu** [comment]
> This is a good proposal, and a complete test is necessary @JulianFeinauer . I can try to use pytest to implement tests on various data type queries. @SteveYurongSu

Great!

**Comment by fuwei3140** [comment]
Hello @JulianFeinauer @SteveYurongSu , 
1.Added test cases to verify query operations of multiple data types, simple queries, queries with null values, and multiple batch queries.
2.Modify the null value handling of the dataframe. In the original implementation, when the data type is INT32, INT64, and BOOLEAN, using 0 and False instead of null values will mislead users and fail to recognize null values. Because numpy does not support null values of this types, the new implementation is to use pd.NA instead of null values of this data types.

**Review by JulianFeinauer — APPROVED** [review]
Thank you very much, I feel a lot better now about this code!

**Comment by fuwei3140** [comment]
fix a bug

**Review by SteveYurongSu — APPROVED** [review]
LGTM! Thanks for your contribution! 

I made some minor changes by executing `black .`(autoformatting) and `flake8 .`(linting) respectively.

**Pull request merged**
