### PR TITLE
[IOTDB-1050] Count timeserise column name is wrong

### PR DESCRIPTION
**Pull request by Genius-pig**
https://issues.apache.org/jira/browse/IOTDB-1050

### CODE REVIEW

**Review by SilverNarcissus — APPROVED** [review]
Nice work. LGTM~

**Review by jixuan1989 — CHANGES_REQUESTED** [review]
UT please

**Comment by Genius-pig** [comment]
> UT please

@jixuan1989 add it in `IoTDBMetadataFetchIT` which uses JDBC or create a new dataset UT? or both of them?

**Comment by qiaojialin** [comment]
@Genius-pig  UT is enough

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
