### PR TITLE
[IOTDB-2173] Update document about group by level clause

### PR DESCRIPTION
**Pull request by Alima777**

### CODE REVIEW

**Comment by SteveYurongSu** [comment]
Please modify CQ's docs :D

**Comment by Alima777** [comment]
> Please modify CQ's docs :D

**Comment by Alima777** [comment]
> Please modify CQ's docs :D

Thanks for your excellent work, it basiclly needs no modification.

**Review by wangchao316 — APPROVED** [review]
LGTM

**Pull request merged**
