### PR TITLE
[IOTDB-1248] forward the pull schema request to the leader

### PR DESCRIPTION
**Pull request by wangchao316**
forward the pull schema request to the leader
For details, please see:

https://shimo.im/docs/wJVKTvKcyJRhGQvg/

### CODE REVIEW

**Comment by wangchao316** [comment]
@neuyilan @mychaow @LebronAl  hi, could you please review?
 Thanks

**Review by LebronAl — APPROVED** [review]
LGTM~
But we may need to manually test again to verify whether the bug descriped in the doc has been eliminated :)

**Review by neuyilan — APPROVED** [review]
Thanks for your efforts!

**Review by mychaow — APPROVED** [review]
LGTM

**Pull request merged**
