### PR TITLE
Remove sqlalchemy upper version constraint for python client

### PR DESCRIPTION
**Pull request by MarcBresson**
## Description

There are only a few breaking changes listed in https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#the-1-4-2-0-migration-path, and not is impacting this project.

Closes https://github.com/apache/iotdb/issues/13991

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by CritasWang** [comment]
@MarcBresson 

There are still some issues that require further modifications

https://github.com/apache/iotdb/actions/runs/11910341559/job/33262355435?pr=14083
https://github.com/apache/iotdb/actions/runs/11910341559/job/33262354350?pr=14083

**Comment by MarcBresson** [comment]
FYI, the reason why I can't run the tests locally is because I have the following error : `ModuleNotFoundError: No module named 'iotdb.thrift'`, that's why I need to do back and forth with the CI pipeline.

**Comment by HTHou** [comment]
Hi, thanks for your work. It seems that the CI with sqlalchemy 2.0 finally works. However, the tests with sqlalchemy 1.4 failed. Is there any way we can support both 1.4 and 2.0?

**Comment by HTHou** [comment]
Ok, still have some tests failed. It looks like caused by my PR https://github.com/apache/iotdb/pull/14232. 
```
from iotdb.IoTDBContainer import IoTDBContainer
```
changed to
```
from tests.integration.iotdb_container import IoTDBContainer
```

**Comment by HTHou** [comment]
Good job! LGTM

**Comment by MarcBresson** [comment]
Thank you! That was a long running PR :) I'm happy to see it merged

**Pull request merged**
