### PR TITLE
[IOTDB-1172] Remove unexpected exception thrown when all CreateTimeseries opeartions are successful for CreateMultiTimeseries

### PR DESCRIPTION
**Pull request by LebronAl**

### CODE REVIEW

**Comment by neuyilan** [comment]
Hi, @LebronAl this bug has been fixed together in this pr
https://github.com/apache/iotdb/pull/2698

**Comment by LebronAl** [comment]
> Hi, @LebronAl this bug has been fixed together in this pr
> #2698

Hi, I think it's unnecessary to record every status to multiPlan.results even all opeartions are successful, which means `multiPlan.getResults().put(i, RpcUtils.getStatus(TSStatusCode.SUCCESS_STATUS));` can be deleted.
What's your opinion?

**Comment by neuyilan** [comment]
> > Hi, @LebronAl this bug has been fixed together in this pr
> > #2698
> 
> Hi, I think it's unnecessary to record every status to multiPlan.results even all opeartions are successful, which means `multiPlan.getResults().put(i, RpcUtils.getStatus(TSStatusCode.SUCCESS_STATUS));` can be deleted.
> What's your opinion?

Indeed, if all operations are successful, it is relatively friendly to delete the above codes, after this pr is merged, I'll merge these codes to #2698

**Review by neuyilan — APPROVED** [review]
LGTM

**Review by mychaow — APPROVED** [review]
LGTM

**Pull request merged**
