### PR TITLE
[IOTDB-2116] Fix all client connections are stuck bug caused by logback bug

### PR DESCRIPTION
**Pull request by JackieTien97**

### CODE REVIEW

**Review by wangchao316 — APPROVED** [review]
LGTM

**Comment by mychaow** [comment]
what is the bug?

**Comment by wangchao316** [comment]
> what is the bug?

Frequent log printing may cause lock requisition, affecting performance. We've met before

**Comment by mychaow** [comment]
> > what is the bug?
> 
> Frequent log printing may cause lock requisition, affecting performance. We've met before

Is audit log frequenct?

**Comment by wangchao316** [comment]
> > > what is the bug?
> > 
> > 
> > Frequent log printing may cause lock requisition, affecting performance. We've met before
> 
> Is audit log frequenct?

yes

**Review by HTHou — APPROVED** [review]

**Comment by mychaow** [comment]
> > > > what is the bug?
> > > 
> > > 
> > > Frequent log printing may cause lock requisition, affecting performance. We've met before
> > 
> > 
> > Is audit log frequenct?
> 
> yes

I have searched the code, and found that the debug audit log is frequent, but info audit log is not frequent, only delete and create meta is log. So, this bug is info log or debug log?

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
