### PR TITLE
[IOTDB-3388] Let MQTT Service could parse JSON array of existed format

### PR DESCRIPTION
**Pull request by LIU-WEI-git**
See [IOTDB-3388](https://issues.apache.org/jira/browse/IOTDB-3388).
Optimize JSONPayloadFormatter. Now MQTT Service could parse not only JSON object, but JSON array.

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, consider adding an example in https://github.com/apache/iotdb/tree/master/example/mqtt/src/main/java/org/apache/iotdb/mqtt ?

**Comment by LIU-WEI-git** [comment]
> Hi, consider adding an example in https://github.com/apache/iotdb/tree/master/example/mqtt/src/main/java/org/apache/iotdb/mqtt ?
> 
> And test cases as well.

Done. Please take a look.

**Comment by wangchao316** [comment]
hi  wei, Will  MQTT Be support in 0.14 version ?

**Comment by LIU-WEI-git** [comment]
> hi wei, Will MQTT Be support in 0.14 version ?

Hi, MQTT service has already been supported in 0.13.

**Review by HTHou — APPROVED** [review]

**Pull request merged**
