### PR TITLE
[To ref/0.12] close compaction by default

### PR DESCRIPTION
**Pull request by mychaow**
## Description

close compaction and adjust the file size threshold 

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by wangchao316** [comment]
hi, chao. this error need see....
Error:  Failures: 
Error:    IoTDBMergeIT.testShowMergeStatus:383 expected:<4> but was:<0>

**Comment by qiaojialin** [comment]
Hi, all bugs of compaction is fixed, we could open it by default

**Comment by mychaow** [comment]
> Hi, all bugs of compaction are fixed, we could open it by default

maybe we could vote for close compaction by default ?

**Comment by mychaow** [comment]
> hi, chao. this error need see....
> Error: Failures:
> Error: IoTDBMergeIT.testShowMergeStatus:383 expected:<4> but was:<0>

thanks, If we close compaction by default, I will fixed it.

**Comment by qiaojialin** [comment]
Hi, we could discuss this on mail list~

**Pull request closed without merging**
