### PR TITLE
add metric framework for iotdb

### PR DESCRIPTION
**Pull request by mychaow**
## Description
This PR adds a measurement data collection system to iotdb, which can be used to monitor the running state of the system.

The system has two characteristics

1. Define the interface of measurement collection system, including measurement collection, and measurement data exposure. You can customize your own implementation based on these interfaces.

      1. There are five kinds of measurement collection interfaces
               1. Counter: can only be incremented
               2. Gauge:  instantaneous value, can be set and obtained
               3.  Rate: throughput, support 1 minute, 5 minutes, 15 minutes of throughput
               4. Histogram:  histogram, support multiple percentage values
               5. Timer:  which can be understood as histogram plus rate
      2. The measurement data exposure interface only defines the start and stop interfaces

2. At present, the implementation based on dropwizard and the implementation based on micrometer are provided. The default is the implementation of micrometer, which supports data exposure to Jmx and Prometheus

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by jixuan1989** [comment]
PR description needed, e.g., the goal, the design, etc..

**Comment by JulianFeinauer** [comment]
Just as a comment, thbis is somewhat related to https://github.com/apache/iotdb/pull/1303.
So if this one gets merged I think we could close the other one, right?

**Comment by jixuan1989** [comment]
Hi,  
a new PR finishes this feature, see
https://github.com/apache/iotdb/pull/4194
Chinese document:
 https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=184616789
English document:
https://cwiki.apache.org/confluence/display/IOTDB/Monitor+Module

**Comment by SteveYurongSu** [comment]
The new metrics framework has been accepted by the community, and the implementation of this PR has been referenced. 

Thanks for the contribution! @mychaow @JulianFeinauer 

I will close this PR.

**Pull request closed without merging**
