### PR TITLE
[IOTDB-2634] Fix batch script exit directly from cmd.exe

### PR DESCRIPTION
**Pull request by ericpai**
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2634

### CODE REVIEW

**Comment by ericpai** [comment]
@HTHou PTAL

**Comment by ericpai** [comment]
It seems that the exit code is not as expected, I will check this later.

**Comment by ericpai** [comment]
@HTHou I have tested both in cmd.exe and Powershell, they all only exit the .bat, not the terminal.

**Comment by HTHou** [comment]
> @HTHou I have tested both in cmd.exe and Powershell, they all only exit the .bat, not the terminal.



**Review by HTHou — APPROVED** [review]
Tested.

**Pull request merged**
