### PR TITLE
[IOTDB-2325] Fix config manual which is different with system config

### PR DESCRIPTION
**Pull request by samperson1997**
**Modified:**
Default value of `concurrent_query_thread` is moidified in PR #4664
Description and default value of `chunk_timeseriesmeta_free_memory_proportion` is modified in PR #4350

**Added:** 
`concurrent_sub_rawQuery_thread` from PR #4664
`raw_query_blocking_queue_capacity` from  PR #4664
`tag_attribute_flush_interval` from PR #4020
`time_index_memory_proportion` from PR #4003
`tracing_dir` from PR #2411
`virtual_storage_group_num` which appears twice

**Deleted:** 
`performance_stat_display_interval` in PR #4556
`time_series_data_type` in PR #3847

**Others:**
`:B:` which turns into emoji
`[xsy]` which is name of a contributor in PR #3071
Add title for index configurations

### CODE REVIEW

**Comment by samperson1997** [comment]
Please help and confirm the changes related, thanks! @Alima777 @zyk990424 @JackieTien97 @Cpaulyz @stormbroken @liutaohua @HTHou @SilverNarcissus

**Review by SilverNarcissus — APPROVED** [review]
Brilliant work! Confirmed. 💯 🥇

**Review by zyk990424 — APPROVED** [review]
Confirmed!

**Review by Cpaulyz — APPROVED** [review]
Confirmed, thanks~

**Review by stormbroken — APPROVED** [review]

**Comment by stormbroken** [comment]
Confirmed, excellent job!

**Review by HTHou — APPROVED** [review]

**Pull request merged**
