### PR TITLE
getObject should not return String for all data types

### PR DESCRIPTION
**Pull request by Alima777**
It's described in https://github.com/apache/iotdb/issues/2169

### CODE REVIEW

**Review by jixuan1989 — CHANGES_REQUESTED** [review]
UT please

**Comment by jixuan1989** [comment]
image

By the way, please check how we use the charset in other codes.

**Comment by Alima777** [comment]
> UT please

Hi, I have added tests and comments for all getValue methods, like getInt(), getLong(), getDouble()...getObject().

**Review by qiaojialin — APPROVED** [review]

**Comment by qiaojialin** [comment]
has cherry-picked to rel/0.11

**Pull request merged**
