### PR TITLE
[IOTDB-845]Enable to stop iotdb server by iotdb.IoTDB

### PR DESCRIPTION
**Pull request by yhwangBonc**

### CODE REVIEW

**Review by neuyilan — APPROVED** [review]

**Comment by jixuan1989** [comment]
> plase make sure only the IoTDB instance under the dir can be stopped.

big +1

By the way, @wyh-ztf  can you create a jira issue to describe current behavior and the new behavior after fixing it?

**Comment by jixuan1989** [comment]
And this issue reminds me another issue: on WinOS, our start-server.bat shell only requires 2GB memory from the OS, while the start-server.sh will use 1/4 memory. I think it also needs to be fixed.

**Comment by wyh-ztf** [comment]
> > plase make sure only the IoTDB instance under the dir can be stopped.
> 
> big +1
> 
> By the way, @wyh-ztf can you create a jira issue to describe current behavior and the new behavior after fixing it?

OK, I've created it

**Comment by wyh-ztf** [comment]
> And this issue reminds me another issue: on WinOS, our start-server.bat shell only requires 2GB memory from the OS, while the start-server.sh will use 1/4 memory. I think it also needs to be fixed.

OK, I'll change it. Thank you for your advice

**Comment by wyh-ztf** [comment]
> > > plase make sure only the IoTDB instance under the dir can be stopped.
> > 
> > 
> > big +1
> > By the way, @wyh-ztf can you create a jira issue to describe current behavior and the new behavior after fixing it?
> 
> OK, I've created it

https://issues.apache.org/jira/browse/IOTDB-845?jql=issuetype%20%3D%20Improvement%20AND%20assignee%20in%20(EMPTY)%20order%20by%20lastViewed%20DESC

**Comment by qiaojialin** [comment]
Hi, I start two IoTDB in my mac, the port is 6667 and 6668. When I try to use ./sbin/stop-server.sh under one IoTDB. it prints the following and does not take effect. Please have a check.

image

**Comment by wyh-ztf** [comment]
> Hi, I start two IoTDB in my mac, the port is 6667 and 6668. When I try to use ./sbin/stop-server.sh under one IoTDB. it prints the following and does not take effect. Please have a check.
> 
> image

Thanks for your advice. I'll check it

**Review by qiaojialin — APPROVED** [review]

**Comment by qiaojialin** [comment]
Hi， please recover the set memory in iotdb-env.bat

**Comment by yhwangBonc** [comment]
> Hi， please recover the set memory in iotdb-env.bat

Ok,I annotated one and put it at the end

**Comment by jixuan1989** [comment]
Hi, I like the changes in `iotdb-env.bat`, good job!

But let's consider the stop script...

Suppose your IoTDB start-server script is at `~/Download/apache/sbin/`,

and your current `pwd` is  `~`, then you can start the IoTDB by `~/Download/iotdb/sbin/start-server.sh`.

Then if you want to stop IoTDB using your script, you must make sure you are in `~`.
Suppose you are now in `~/Download`, and if you call `iotdb/sbin/stop-server.sh`, you will get `No IoTDB server to stop`.

**Comment by yhwangBonc** [comment]
> Hi, I like the changes in `iotdb-env.bat`, good job!
> 
> But let's consider the stop script...
> 
> Suppose your IoTDB start-server script is at `~/Download/apache/sbin/`,
> 
> and your current `pwd` is `~`, then you can start the IoTDB by `~/Download/iotdb/sbin/start-server.sh`.
> 
> Then if you want to stop IoTDB using your script, you must make sure you are in `~`.
> Suppose you are now in `~/Download`, and if you call `iotdb/sbin/stop-server.sh`, you will get `No IoTDB server to stop`.

You're right. I'll try to stop the service by getting the process number through the port number

**Pull request merged**
