### PR TITLE
[IOTDB-2797] Use path pattern to check path in Auth

### PR DESCRIPTION
**Pull request by LIU-WEI-git**
Revert PR #5756 and use path pattern in auth check.
See [IOTDB-2797](https://issues.apache.org/jira/browse/IOTDB-2797) and the mail [Refactor the rule of auth check](https://lists.apache.org/thread/y9god4drws6x527qfcyonyyrro9j6qkn).

### CODE REVIEW

**Review by SpriCoder — APPROVED** [review]
LGTM！

**Comment by SpriCoder** [comment]
PTAL, there are some conflicts.

**Review by MarcosZyk — APPROVED** [review]
Excellent work! LGTM~

**Comment by MarcosZyk** [comment]
@RYH61 PTAL

**Review by RYH61 — APPROVED** [review]

**Pull request merged**
