### PR TITLE
[IOTDB-5796][IOTDB-5701] Remove recorder and optimize the usage of metrics

### PR DESCRIPTION
**Pull request by SpriCoder**
This PR is mainly focused on the metric module and optimizes the implementation of the metric module. The details are as follows.
1. Unify the access of metric service in nodeManager about partition.
2. Optimize the metrics in the IoT Consensus module: optimize access way and related metric sets.
3. Optimize the implementation of the Metric enum, split different metric names into sections, and add a parameter to avoid toString() cost.
4. Optimize the implementation of the Tag, CompactionType, ProcessChunkType, and CheckpointType enum, and add a parameter to avoid toString() cost.
5. Optimize ChunkCacheMetrics and fix class cast.
6. Merge CacheMetrics and CacheMetricsRecorder to manage partition cache-related metrics.
7. Merge CompactionMetrics and CompactionManage to manage compaction-related metrics. At the same time, fix 2 problems that are forgetting to divide 1024 in the read scenario and forgetting to update the summary before updation.
8. Merge Writing Metrics and WritingMetircsManager to manage writing-related metrics.
9. Merge query-related metrics with QueryMetricManager to reduce cost.

### CODE REVIEW

**Review by CRZbulabula — APPROVED** [review]
These elegant codes are LGTM~~~~~~~~~~~

**Review by THUMarkLau — APPROVED** [review]
LGTM

**Review by JackieTien97 — APPROVED** [review]

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Review by HTHou — APPROVED** [review]
LGTM about the storage engine part

**Pull request merged**
