### PR TITLE
[IOTDB-5618] Add RatisConsensus metrics in dashboard

### PR DESCRIPTION
**Pull request by BUAAserein**
#### Average Time Consumed Of Write Stage
It shows the time of wirting stages in RatisConsensus.

image

#### Average Time Consumed Of Read Stage
It shows the time of reading stages in RatisConsensus.

image

#### Write Ratis
It shows the time of wirting ratis roughly.

image

#### Leader Write Ratis Log
It shows the time of wirting ratis in detail (leader writes the records to its raft log).

image

#### RatisConsensus Memory
It shows some memory metris in ratis.

image

### CODE REVIEW

**Review by SzyWilliam — COMMENTED** [review]
@BUAAserein Thanks very much for working on this, excellent job!
Shall we also add descriptions of ratis-native metrics to the doc?

**Comment by BUAAserein** [comment]
> @BUAAserein Thanks very much for working on this, excellent job! Shall we also add descriptions of ratis-native metrics to the doc?

Thanks for the advice. I'll add the metrics to the doc for clarity.

**Comment by BUAAserein** [comment]
image

**Comment by BUAAserein** [comment]
image

**Comment by BUAAserein** [comment]
image

**Comment by BUAAserein** [comment]
The performance test results：

image

Please see details in [feishu doc](https://apache-iotdb.feishu.cn/docx/doxcnU3YAVr4JIlEIOmQyVEzTth).

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM~
Awesome work!

**Review by SzyWilliam — APPROVED** [review]
Thanks very much for @BUAAserein to working on this! It's bravo to see such a delightful panel. ❤️ Also it's good to know the performance dropdown is of minor concern. 
Again, great job!

**Pull request merged**
