### PR TITLE
[IOTDB-1126] [To rel/0.11]cherry pick IOTDB-1126 unseq tsfile delete due to merge (#2577)

### PR DESCRIPTION
**Pull request by wangchao316**
cherry pick from master branch, merged to 0.11.

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, we usually add the `[To rel/0.11]` on the title for those PR commit into `rel/0.11`. So that we can see this PR is not for master branch easily.

**Comment by wangchao316** [comment]
> Hi, we usually add the `[To rel/0.11]` on the title for those PR commit into `rel/0.11`. So that we can see this PR is not for master branch easily.

Thanks @HTHou , I will alter this.

**Comment by wangchao316** [comment]
> > Hi, we usually add the `[To rel/0.11]` on the title for those PR commit into `rel/0.11`. So that we can see this PR is not for master branch easily.
> 
> Thanks @HTHou , I will alter this.

hi @HTHou ,could you merged this ?

**Comment by HTHou** [comment]
> hi @HTHou ,could you merged this ?
Sure.

**Pull request merged**
