### PR TITLE
Fix thread safety issues in SyncServerManager

### PR DESCRIPTION
**Pull request by asdf2014**

### CODE REVIEW

**Comment by jixuan1989** [comment]
why add `sync` keywork on these two methods.

**Comment by qiaojialin** [comment]
Hi,  the synchronized in ThriftService could be removed, what do you think~

**Comment by asdf2014** [comment]
@qiaojialin Thanks for your comments. Indeed, I have removed the useless `synchronized` keyword from `ThriftService`.

**Review by qiaojialin — APPROVED** [review]
LGTM~

**Comment by qiaojialin** [comment]
Why does not the CI run...

**Comment by asdf2014** [comment]
@qiaojialin Not sure. I don’t have permission to rerun CI tasks :sweat_smile:

**Comment by HTHou** [comment]
Hi, I think CI has been fixed, plz merge the master branch.

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
