### PR TITLE
IOTDB-986 when path node is empty, throw an exception

### PR DESCRIPTION
**Pull request by Genius-pig**
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986

### CODE REVIEW

**Review by Alima777 — APPROVED** [review]
LGTM

**Comment by LebronAl** [comment]
I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL

**Comment by Genius-pig** [comment]
> I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL

**Comment by Genius-pig** [comment]
> I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL

in JDBC, it can use antlr to check the path.

**Comment by LebronAl** [comment]
> > I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL
> 
> in JDBC, it can use antlr to check the path.

OK~Then please take a check about auto-creating-schema in `insertRowPlan` and `insertTabletPlan`.

**Comment by Genius-pig** [comment]
> > > I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL
> > 
> > 
> > in JDBC, it can use antlr to check the path.
> 
> OK~Then please take a check about auto-creating-schema in `insertRowPlan` and `insertTabletPlan`.

you mean in JDBC or session?

**Comment by LebronAl** [comment]
session

**Comment by LebronAl** [comment]
> > > > I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL
> > > 
> > > 
> > > in JDBC, it can use antlr to check the path.
> > 
> > 
> > OK~Then please take a check about auto-creating-schema in `insertRowPlan` and `insertTabletPlan`.
> 
> you mean in JDBC or session?

session

**Comment by Genius-pig** [comment]
> > > > > I have updated the description of [IOTDB-986](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-986)~PTAL
> > > > 
> > > > 
> > > > in JDBC, it can use antlr to check the path.
> > > 
> > > 
> > > OK~Then please take a check about auto-creating-schema in `insertRowPlan` and `insertTabletPlan`.
> > 
> > 
> > you mean in JDBC or session?
> 
> session

I add two tests in IoTDBSessionSimpleIT with the wrong path, but it didn't create schema successfully

**Comment by LebronAl** [comment]
great job!

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
