### PR TITLE
IOTDB-1250 fix pull schema bug

### PR DESCRIPTION
**Pull request by mychaow**
## Description

see https://issues.apache.org/jira/browse/IOTDB-1250

fix bug when pull schema.

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [x] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by jt2594838** [comment]
image
I think the root is that `pullTimeSeriesSchema` is misused here, which should be `pullMeasurementSchema`.

**Comment by mychaow** [comment]
> image
> I think the root is that `pullTimeSeriesSchema` is misused here, which should be `pullMeasurementSchema`.

yes, you are right, I will add comment for the two method, it's confused.

**Review by LebronAl — APPROVED** [review]
LGTM

**Review by neuyilan — APPROVED** [review]
LGTM

**Pull request merged**
