### PR TITLE
[To rel/0.12] [IOTDB-2072] Remove TVListAllocator to reduce the TVList mem cost

### PR DESCRIPTION
**Pull request by HTHou**
## Description

Method 2 to reduce the TVList mem cost.

After release the TVList, the empty Object array in arrayList is not trimmed but put back to the cache of TVListAllocator. If a longer TVList reused by a shorter TVList, the memory is wasted.

Therefore, removing TVListAllocator and avoid reusing the TVList is another way to reduce TVList mem cost.

### CODE REVIEW

**Review by qiaojialin — APPROVED** [review]

**Comment by HTHou** [comment]
44081638928863_ pic_hd

Removing TVListAllocator also improved the write performance. The reason is we don't need to hold the lock to apply and release TVList.

**Comment by mychaow** [comment]
So, we do not reuse the tvlist, every time we allocate a new one when insert?

**Comment by HTHou** [comment]
> So, we do not reuse the tvlist, every time we allocate a new one when insert?

Yes. And it seems that it doesn't have negative effect.

**Review by mychaow — APPROVED** [review]
LGTM

**Pull request merged**
