### PR TITLE
[IOTDB-4153]Grant ALL privileges to different paths return privilege exists

### PR DESCRIPTION
**Pull request by yifuzhou**
[IOTDB-4153](https://issues.apache.org/jira/browse/IOTDB-4153)

If meet path independent privileges likes 'ALL', 'CREATE_ROLE', we cannot grant or revoke on any path except for root.**.

image

### CODE REVIEW

**Comment by yifuzhou** [comment]
@RYH61 @MarcosZyk @qiaojialin @SpriCoder Hi, can you review it? Thanks!

**Comment by RYH61** [comment]
Please add userGuide~

**Comment by yifuzhou** [comment]
> Please add userGuide~

**Review by RYH61 — APPROVED** [review]
LGTM~

**Review by wangchao316 — APPROVED** [review]
LGTM

**Comment by SpriCoder** [comment]
LGTM~

**Review by SpriCoder — APPROVED** [review]

**Review by MarcosZyk — APPROVED** [review]
Nice work! LGTM.

**Pull request merged**
