### PR TITLE
Fix grafana user guide

### PR DESCRIPTION
**Pull request by stormbroken**
I encountered grafana prompt unsigned plugins after I install simple-json plugins, and I want to specific related docs

### CODE REVIEW

**Review by qiaojialin — COMMENTED** [review]
Hi, we have a grafana userguide in docs/Userguide, please fix there, it is where our official website use

**Comment by stormbroken** [comment]
Ok, I have fixed grafana userguide in docs/Userguide, thanks for your suggestions.

**Comment by HTHou** [comment]
Hi, does English need to be updated too?

**Comment by stormbroken** [comment]
Yes, I check English doc and add some description.

**Review by HTHou — APPROVED** [review]
LGTM

**Pull request merged**
