### PR TITLE
[IOTDB-1629] fix the NPE when using value fill in cluster mode

### PR DESCRIPTION
**Pull request by cornmonster**
For more detailed descriptions: https://issues.apache.org/jira/browse/IOTDB-1629

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, thanks for your contribution!

How about adding some UT or IT?

**Comment by cornmonster** [comment]
> Hi, thanks for your contribution!
> 
> How about adding some UT or IT?


> Hi, thanks for your contribution!
> 
> How about adding some UT or IT?

Sure. But this issue is related to another one, please see https://issues.apache.org/jira/browse/IOTDB-1632. The value fill function currently produces incorrect results, and that's why the unit test fails right now.

**Comment by LebronAl** [comment]
Hi, How about fixing them both in this PR?

**Comment by cornmonster** [comment]
> Hi, How about fixing them both in this PR?

There is already another PR for https://issues.apache.org/jira/browse/IOTDB-1632, please see: https://github.com/apache/iotdb/pull/3914

This PR should pass the CI tests once PR #3914 merged.

**Comment by LebronAl** [comment]
> > Hi, How about fixing them both in this PR?
> 
> There is already another PR for https://issues.apache.org/jira/browse/IOTDB-1632, please see: #3914
> 
> This PR should pass the CI tests once PR #3914 merged.

OK!You can do it now!

**Comment by cornmonster** [comment]
> > > Hi, How about fixing them both in this PR?
> > 
> > 
> > There is already another PR for https://issues.apache.org/jira/browse/IOTDB-1632, please see: #3914
> > This PR should pass the CI tests once PR #3914 merged.
> 
> OK!You can do it now!

Thanks! I have rebased the code and all tests are passing now.

**Review by LebronAl — COMMENTED** [review]
Do you think that we need a `ClusterValueFill` just like `ClusterLinearFill` and `ClusterPreviousFill`?

**Comment by cornmonster** [comment]
> Do you think that we need a `ClusterValueFill` just like `ClusterLinearFill` and `ClusterPreviousFill`?

Nope, I believe we have `ClusterLinearFill` and `ClusterPreviousFill` because they need to access the storage engine, and the way of accessing the storage engine in cluster mode is different from the standalone mode. ValueFill doesn't require any context except the input constant, so implementing the `ClusterValueFill` may not be necessary.

**Review by LebronAl — APPROVED** [review]
LGTM

**Comment by mychaow** [comment]
please cherry pick to 0.12

**Pull request merged**
