### PR TITLE
[IOTDB-6245] Load: Adjust forceCloseWriterManager execution delay in LoadTsFileManager to 15mins to avoid OOM & clear all data structures after use to help GC

### PR DESCRIPTION
**Pull request by MiniSho**
## Description

1. Adjust forceCloseWriterManager execution delay in LoadTsFileManager to 15mins to avoid OOM 
2. Clear all data structures after use to help GC

### CODE REVIEW

**Review by SteveYurongSu — APPROVED** [review]

**Review by SteveYurongSu — CHANGES_REQUESTED** [review]
Fix CI please

**Review by SteveYurongSu — APPROVED** [review]

**Review by SteveYurongSu — CHANGES_REQUESTED** [review]
CAN BE BETTER:)

**Review by yschengzi — APPROVED** [review]
LGTM

**Review by SteveYurongSu — APPROVED** [review]

**Review by wangchao316 — APPROVED** [review]
LGTM

**Pull request merged**
