### PR TITLE
[IOTDB-1503] 1 node crash causes whole cluster cannot work

### PR DESCRIPTION
**Pull request by jamber001**
### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by jamber001** [comment]
When 1 node crash， other alive nodes need check RPC client connection status.
If the connection is broken, must do client.getInputProtocol().getTransport().close();
Otherwise these failed clients will be put back to client pool, which will cause later cluster error.

Note: IoTDB currrent Try-with-Resource codes can not avoid this error.

**Review by wangchao316 — COMMENTED** [review]
Good Job.
this pr solved this issue, you see:
https://github.com/apache/iotdb/pull/3580

**Comment by HTHou** [comment]
> Good Job.
> this pr solved this issue, you see:
> #3580

Hi Chao, #3580 is trying to commit into rel/0.12. We can compare and discuss this two PR here.

**Comment by HTHou** [comment]
> Good Job.
> this pr solved this issue, you see:
> #3580

Hi Chao, #3580 is trying to commit into rel/0.12. We can compare and discuss this two PR here.

**Review by wangchao316 — APPROVED** [review]
LGTM

**Review by LebronAl — APPROVED** [review]
LGTM

**Pull request merged**
