### PR TITLE
[IOTDB-2824] fix stop-server.sh that wrongly kill process

### PR DESCRIPTION
**Pull request by jamber001**
https://issues.apache.org/jira/browse/IOTDB-2824

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, would you like to cherry pick this bug-fix PR to `rel/0.13` branch?

**Review by HTHou — APPROVED** [review]
LGTM
Already tested on my local macos machine.

**Comment by jamber001** [comment]
> Hi, would you like to cherry pick this bug-fix PR to `rel/0.13` branch?

No problem.  :-)

**Comment by jamber001** [comment]
> LGTM Already tested on my local macos machine.

Thank you.  ^-^

**Pull request merged**
