### PR TITLE
[ISSUE-2585] show devices with storage group

### PR DESCRIPTION
**Pull request by haimeiguo**
add new sql grammar 
”show devices with storage group“
```
IoTDB> show devices with storage group
+--------------+-------------+
|       devices|storage group|
+--------------+-------------+
|   root.sg1.d1|     root.sg1|
|root.sg2.d1.d2|     root.sg2|
|   root.sg2.d2|     root.sg2|
+--------------+-------------+
```

### CODE REVIEW

**Comment by Alima777** [comment]
Hi, thank you for the contribution first :D

However, I am not sure whether we need this new feature. Literally, command `show devices` should not include storage group columns, and even if users want to see, they can also use `show storage group` command.

**Comment by haimeiguo** [comment]
Hi,
show storage group command only supports path to sg level.
ie. root.sg1.d1.s1
"show storage group root.sg1.d1" is not supported.
users want to know which storage group the device belongs to.

**Comment by HTHou** [comment]
What about add a new type of DDL `show devices with storage group`? 😂

**Comment by HTHou** [comment]
Add some user guide?

**Comment by jixuan1989** [comment]
code smell should be fixed: do not just return 0 directly in `compareTo()`

**Review by HTHou — APPROVED** [review]
I have tried this new feature and it works very well.

**Comment by HTHou** [comment]
> Kudos, SonarCloud Quality Gate passed!
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=VULNERABILITY)
> [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=SECURITY_HOTSPOT)
> [Code Smell](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=apache_incubator-iotdb&pullRequest=2475&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=apache_incubator-iotdb&pullRequest=2475) No Coverage information
> [](https://sonarcloud.io/component_measures?id=apache_incubator-iotdb&pullRequest=2475&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache_incubator-iotdb&pullRequest=2475&metric=new_duplicated_lines_density&view=list)

Another code smell.... please take a look.

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
