### PR TITLE
[IOTDB-5297] Add maxRetryTimes for IoTDBClusterNodeErrorStartUpIT to avoid infinite loop

### PR DESCRIPTION
**Pull request by ericpai**
See JIRA: https://issues.apache.org/jira/browse/IOTDB-5297
This PR is a small fix of #8481

### CODE REVIEW

**Comment by ericpai** [comment]
@CRZbulabula PTAL

**Review by Beyyes — APPROVED** [review]
IoTDBClusterNodeErrorStartUpIT is failed
image

**Review by CRZbulabula — APPROVED** [review]
LGTM～

**Comment by ericpai** [comment]
> IoTDBClusterNodeErrorStartUpIT is failed image

@Beyyes The IT case itself contains a bug that asserting 3 nodes ready, not 4. I have fixed it. PTAL

**Pull request merged**
