### PR TITLE
[IOTDB-1133] make the vulnerabilities check configurable

### PR DESCRIPTION
**Pull request by neuyilan**
please see the following link for detail
https://issues.apache.org/jira/browse/IOTDB-1133

### CODE REVIEW

**Review by mychaow — APPROVED** [review]
Good job!

**Review by jixuan1989 — CHANGES_REQUESTED** [review]
Hi,
1. we do not need add any other properties, maven enforcer plugin has its property: just use: `-Denforcer.skip=true`
2. add the parameter to github actions.

**Comment by jixuan1989** [comment]
> Hi,
> 
> 1. we do not need add any other properties, maven enforcer plugin has its property: just use: `-Denforcer.skip=true`
> 2. add the parameter to github actions.

And, if you want to skip the test by default, yes we can set the parameter as true by default.

Only the release manager needs to enable it.

**Comment by qiaojialin** [comment]
+1 to set it to false by default

**Comment by jixuan1989** [comment]
done in #2603

**Pull request closed without merging**
