### PR TITLE
[IOTDB-6191] Fix group by year

### PR DESCRIPTION
**Pull request by Wei-hao-Li**
github issue https://github.com/apache/iotdb/issues/11133
doc https://apache-iotdb.feishu.cn/docx/TNBPd8nZUoDsJMxjdOncOUkcnVA

### CODE REVIEW

**Comment by liuminghui233** [comment]
It is a good idea to add duration unit fields in `GroupByComponent`. But I think we should go one step further - define a `TimeDuration` class like this: 
```java
public class TimeDuration {
    private final long duration;
    private final DurationUnit unit;
}
```

The `GroupByComponent` will then contain the following fields:
```java
// [startTime, endTime)
private long startTime;
private long endTime;

// time interval
private TimeDuration interval;

// sliding step
private TimeDuration slidingStep;

// if it is left close and right open interval
private boolean leftCRightO;
```

I believe this will make the code clearer and more readable.

What do you think? @Wei-hao-Li @JackieTien97

**Comment by JackieTien97** [comment]
> It is a good idea to add duration unit fields in `GroupByComponent`. But I think we should go one step further - define a `TimeDuration` class like this:
> 
> ```java
> public class TimeDuration {
>     private final long duration;
>     private final DurationUnit unit;
> }
> ```
> 
> The `GroupByComponent` will then contain the following fields:
> 
> ```java
> // [startTime, endTime)
> private long startTime;
> private long endTime;
> 
> // time interval
> private TimeDuration interval;
> 
> // sliding step
> private TimeDuration slidingStep;
> 
> // if it is left close and right open interval
> private boolean leftCRightO;
> ```
> 
> I believe this will make the code clearer and more readable.
> 
> What do you think? @Wei-hao-Li @JackieTien97

good idea,  that would be more clear.

**Comment by cqzhang7** [comment]
This PR conflicts with mine,I think the focus should be to evaluate whether this change improves the calculation performance, otherwise why not replace the input '1y' to '12mo', which would be a simple solution, and doesn't introduce any additional computational burden  @HTHou  @JackieTien97

**Comment by liuminghui233** [comment]
> This PR conflicts with mine,I think the focus should be to evaluate whether this change improves the calculation performance, otherwise why not replace the input '1y' to '12mo', which would be a simple solution, and doesn't introduce any additional computational burden @HTHou @JackieTien97

Yes, replacing '1y' with '12mo' might be a simple solution. @Wei-hao-Li  you can think about it.

**Comment by Wei-hao-Li** [comment]
> This PR conflicts with mine,I think the focus should be to evaluate whether this change improves the calculation performance, otherwise why not replace the input '1y' to '12mo', which would be a simple solution, and doesn't introduce any additional computational burden @HTHou @JackieTien97

Your think is right.

**Comment by Wei-hao-Li** [comment]
@cqzhang7 The fixed PR using your method is [here](https://github.com/apache/iotdb/pull/11323) , thanks for your contribution.

**Pull request closed without merging**
