### PR TITLE
add: define a constant instead load manager metrics.

### PR DESCRIPTION
**Pull request by auula**
add define a constant instead #7013.

### CODE REVIEW

**Review by neuyilan — APPROVED** [review]
LGTM

**Comment by HTHou** [comment]
Hi, plz run `mvn spotless:apply` to fix the format issue.

**Comment by auula** [comment]
> Hi, plz run `mvn spotless:apply` to fix the format issue.

I'm not familiar with this project, how do I do it instead?

**Comment by auula** [comment]
> Hi, plz run `mvn spotless:apply` to fix the format issue.

What should I do?

**Comment by auula** [comment]
thank！

**Comment by auula** [comment]
Thank you for your guidance and I hope to merge it into the main branch, thanks 👍

**Pull request merged**
