### PR TITLE
Issue/cleanup config node removal

### PR DESCRIPTION
**Pull request by chrisdutz**
Started updating the config node cli to allow removing config-nodes by ID.

Unfortunately when implementing the unit tests for this, this showed a number of problems in the code, so I guess a real fix for this will requite a bit larger refactoring of the code in general.

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
any updates？

**Comment by chrisdutz** [comment]
This will be replaced by my general refactoring of the clis.

**Comment by chrisdutz** [comment]
This PR is superceded by this one: https://github.com/apache/iotdb/pull/13194

**Comment by OneSizeFitsQuorum** [comment]
Then I will close this pr

**Pull request closed without merging**
