### PR TITLE
[IOTDB-3750] Fix NPE caused by SchemaQueryMergeOperator#next returning null

### PR DESCRIPTION
**Pull request by xinzhongtianxia**
see https://issues.apache.org/jira/browse/IOTDB-3750

### CODE REVIEW

**Review by yifuzhou — APPROVED** [review]
LGTM~

**Comment by MarcosZyk** [comment]
Could you please check the problem on the latest master branch. A huge PR has been merged today to solve a number of schema related problems. The null has been well processed in parent operator.

**Comment by MarcosZyk** [comment]
@JackieTien97 PTAL

**Review by MarcosZyk — APPROVED** [review]
LGTM

**Comment by MarcosZyk** [comment]
The isBlock, hasNext and next method should keep consistent and work on same child.

**Pull request merged**
