### PR TITLE
[IOTDB-6293] Use nanotime in cluster heartbeat

### PR DESCRIPTION
**Pull request by CRZbulabula**
https://issues.apache.org/jira/browse/IOTDB-6293

### CODE REVIEW

**Comment by wangchao316** [comment]
I  have a question , why use nanotime ?  "To prevent the heartbeat bug caused by modifying server clock"

**Comment by OneSizeFitsQuorum** [comment]
>  "To prevent the heartbeat bug caused by modifying server clock"

Yes

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM~
@liyuheng55555 Please notice if you need to change anything in the activation module!

**Comment by liyuheng55555** [comment]
> LGTM~ @liyuheng55555 Please notice if you need to change anything in the activation module!

I've checked activation module, and I'm ready (hope so)

**Pull request merged**
