### PR TITLE
[IOTDB-2671][metrics] Improve the implementation of iotdbReporter

### PR DESCRIPTION
**Pull request by SpriCoder**
See more details:https://issues.apache.org/jira/browse/IOTDB-2671.

### CODE REVIEW

**Comment by SpriCoder** [comment]
@SteveYurongSu PTAL!

**Comment by SteveYurongSu** [comment]
> @SteveYurongSu PTAL!

Hi, great! Please resolve the conflict :D

**Comment by SpriCoder** [comment]
> > @SteveYurongSu PTAL!
> 
> Hi, great! Please resolve the conflict :D

Ok, I resolve the conflict.

**Comment by jun0315** [comment]
LGTM

**Review by SteveYurongSu — APPROVED** [review]
LGTM. 

Maybe we can use SessionPool instead of Session for fault tolerance. This can be a new ticket for u.

**Pull request merged**
