### PR TITLE
[IOTDB-1632] fill only if the value is missing

### PR DESCRIPTION
**Pull request by cornmonster**
For detailed descriptions: https://issues.apache.org/jira/browse/IOTDB-1632

### CODE REVIEW

**Comment by cornmonster** [comment]
@HTHou Hi, could u please have a look at this PR? Thanks for your time.

**Comment by cornmonster** [comment]
I noticed the E2E test failed. Here is the failed test case and it seems to be an unrelated error

```
2021-09-09T10:14:45.8632217Z [ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 730.007 s <<< FAILURE! - in org.apache.iotdb.db.sql.nodes5.FiveNodeCluster2IT
2021-09-09T10:14:45.8638541Z [ERROR] showTimeseriesRowsTest(org.apache.iotdb.db.sql.nodes5.FiveNodeCluster2IT)  Time elapsed: 522.68 s  <<< FAILURE!
2021-09-09T10:14:45.8640357Z java.lang.AssertionError: expected:<3000> but was:<0>
```

**Comment by cornmonster** [comment]
The Sonar-Coveralls test also failed because of an unrelated unit test case:

```
Error:    IoTDBLoadExternalTsfileIT.loadUnsequenceTsfileTest:448 » IoTDBSQL 411: Cannot ...
```

**Comment by HTHou** [comment]
> I noticed the E2E test failed. Here is the failed test case and it seems to be an unrelated error
> 
> ```
> 2021-09-09T10:14:45.8632217Z [ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 730.007 s <<< FAILURE! - in org.apache.iotdb.db.sql.nodes5.FiveNodeCluster2IT
> 2021-09-09T10:14:45.8638541Z [ERROR] showTimeseriesRowsTest(org.apache.iotdb.db.sql.nodes5.FiveNodeCluster2IT)  Time elapsed: 522.68 s  <<< FAILURE!
> 2021-09-09T10:14:45.8640357Z java.lang.AssertionError: expected:<3000> but was:<0>
> ```
> 
> I guess it may be caused by some random reasons. Could you please retry the CI test? Thanks!
> 
> @HTHou

Sure

**Comment by HTHou** [comment]
> The Sonar-Coveralls test also failed because of an unrelated unit test case:
> 
> ```
> Error:    IoTDBLoadExternalTsfileIT.loadUnsequenceTsfileTest:448 » IoTDBSQL 411: Cannot ...
> ```

It is a bug we are fixing. It doesn’t matter.

**Comment by cornmonster** [comment]
I have checked the latest CI test results. There is a new failure Main Win / win (16, server):

```
java.lang.AssertionError
	at org.apache.iotdb.db.integration.IoTDBContinuousQueryIT.checkCQExecutionResult(IoTDBContinuousQueryIT.java:345)
	at org.apache.iotdb.db.integration.IoTDBContinuousQueryIT.testContinuousQueryResult1(IoTDBContinuousQueryIT.java:245)
```

I checked the source code, the IT IoTDBContinuousQueryIT#testContinuousQueryResult1 seems like another unrelated test case.

@Alima777 @neuyilan Could u please help review this PR? Thanks for your time!

**Review by Alima777 — APPROVED** [review]
It looks good to me~ Thank you for the contribution :D

**Review by LebronAl — APPROVED** [review]
LGTM

**Pull request merged**
