### PR TITLE
[Distributed] Fix init serialToParallelPool bug if cpu.cores > 100

### PR DESCRIPTION
**Pull request by LebronAl**
We will encounter a exception when starting cluster server if cpu.cores > 100, so we should change the parameters for `ThreadPoolExecutor`. As `serialToParallelPool` will only do heartbeat or add/remove node, I think the coreSize can be 'allNode.size()', and the maxSize can be set to `Math.max(allNodes.size(), Runtime.getRuntime().availableProcessors())`.

### CODE REVIEW

**Review by neuyilan — APPROVED** [review]
Good Job! besides, envy that you have more than 100 cores servers~

**Comment by LebronAl** [comment]
> Good Job! besides, envy that you have more than 100 cores servers~
Scale up is too nice, I've forgotten how to scale out~

**Comment by LebronAl** [comment]
> int maxConcurrentClientNum = Math.max(CommonUtils.getCpuCores(), config.getMaxConcurrentClientNum());

You are right.But I think the core size can be smaller than cpu.core.What about this:`      serialToParallelPool = new ThreadPoolExecutor(allNodes.size(), Math.max(allNodes.size(), Runtime.getRuntime().availableProcessors()),
          1000L, TimeUnit.MILLISECONDS,
          new LinkedBlockingQueue<>(), new ThreadFactoryBuilder().setNameFormat(getName() +
          "-SerialToParallel%d").build());`

**Comment by neuyilan** [comment]
> > int maxConcurrentClientNum = Math.max(CommonUtils.getCpuCores(), config.getMaxConcurrentClientNum());
> 
> You are right.But I think the core size can be smaller than cpu.core. What about this？` serialToParallelPool = new ThreadPoolExecutor(allNodes.size(), Math.max(allNodes.size(), Runtime.getRuntime().availableProcessors()), 1000L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>(), new ThreadFactoryBuilder().setNameFormat(getName() + "-SerialToParallel%d").build());`

**Comment by neuyilan** [comment]
> > int maxConcurrentClientNum = Math.max(CommonUtils.getCpuCores(), config.getMaxConcurrentClientNum());
> 
> You are right.But I think the core size can be smaller than cpu.core. What about this？` serialToParallelPool = new ThreadPoolExecutor(allNodes.size(), Math.max(allNodes.size(), Runtime.getRuntime().availableProcessors()), 1000L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>(), new ThreadFactoryBuilder().setNameFormat(getName() + "-SerialToParallel%d").build());`

LGTM

**Review by jt2594838 — APPROVED** [review]

**Pull request merged**
