### PR TITLE
[ISSUE-github 3582]Optimize the implementation of singleton;

### PR DESCRIPTION
**Pull request by limeng32**
## Description
Hello everyone, this time the auto-scanning-code check out two classes a bit flawed, by carefully look at the two classes it is a singleton using the hungry-mode. There is a little danger, I change them into using static-internal-class like most other classes. The two class files are: UpgradeSevice .java and TVListAllocator .java.

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Comment by HTHou** [comment]
Run `mvn spotless:apply` to format the code?

**Comment by limeng32** [comment]
Yes. If I don`t do this, I can`t do mvn test.

**Comment by limeng32** [comment]
Something wrong with my IDE, I will post the pr again.

**Pull request closed without merging**
