### PR TITLE
[IOTDB-2462] Fix ALIGN BY DEVICE query in cluster mode

### PR DESCRIPTION
**Pull request by ericpai**
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2462
The Thrift interface `getAllDevices()` is changed. Does it cause imcompatiable with previsous version, or Thrift framework can handle this upgrade?

### CODE REVIEW

**Comment by ericpai** [comment]
@Alima777 @zyk990424 PTAL.

**Comment by ericpai** [comment]
@qiaojialin This is a bug fix of an existence feature. Should it be patched into v0.13.0 or any later versions?

**Review by zyk990424 — APPROVED** [review]
Wonderful work! Thanks for fixing. LGTM~

**Comment by Alima777** [comment]
LGTM~Thank you

**Review by Alima777 — APPROVED** [review]

**Pull request merged**
