### PR TITLE
[IOTDB-2541] Enhance /ping API to liveness probe

### PR DESCRIPTION
**Pull request by ericpai**
See JIRA: https://issues.apache.org/jira/browse/IOTDB-2541

### CODE REVIEW

**Comment by ericpai** [comment]
@SteveYurongSu @CloudWise-Lukemiao PTAL

**Comment by SteveYurongSu** [comment]
Thanks for your contribution :D 
I will take a look ASAP.

**Comment by ericpai** [comment]
@SteveYurongSu is there any other questions?

**Review by SteveYurongSu — APPROVED** [review]
LGTM

**Comment by SteveYurongSu** [comment]
> @SteveYurongSu is there any other questions?

Sorry for the late reply. The PR looks great :D

**Pull request merged**
