### PR TITLE
[To rel/0.12][IOTDB-1600] Support InsertRowsOfOneDevicePlan in cluster

### PR DESCRIPTION
**Pull request by ericpai**
See JIRA: https://issues.apache.org/jira/browse/IOTDB-1600 . Cherry-picked from https://github.com/apache/iotdb/pull/3877

### CODE REVIEW

**Comment by ericpai** [comment]
I have cherry-picked the code change except for testcontainer ones.

**Comment by ericpai** [comment]
@LebronAl This should be patched to rel/0.12 as it's a bug fix.

**Comment by HTHou** [comment]
Hi, can you plz update the RELEASE_NOTE of 0.12.2 in this PR. We can put this commit into 0.12.2 RC3.

**Comment by ericpai** [comment]
> Hi, can you plz update the RELEASE_NOTE of 0.12.2 in this PR. We can put this commit into 0.12.2 RC3.

Release note has been updated. I labeled this as a bugfix.

**Review by HTHou — APPROVED** [review]

**Pull request merged**
