### PR TITLE
[IOTDB-4055] Add remove-confignode.bat

### PR DESCRIPTION
**Pull request by MiniSho**
1. Add remove-confignode.bat
2. update UserGuide

### CODE REVIEW

**Review by Beyyes — COMMENTED** [review]
any running screenshots on windows~?

**Comment by MiniSho** [comment]
4362a9a6a92fe25522b5b77702f3b5c

**Comment by MiniSho** [comment]
4362a9a6a92fe25522b5b77702f3b5c

**Comment by CRZbulabula** [comment]
Please add the screenshot of invoking the show cluster command ~

**Comment by MiniSho** [comment]
127e11c278b632bd54c90e8a38aea92

**Review by CRZbulabula — APPROVED** [review]
LGTM～

**Review by Beyyes — APPROVED** [review]

**Pull request merged**
