### PR TITLE
 [IOTDB-2181] Fix cluster tag

### PR DESCRIPTION
**Pull request by cornmonster**
See: https://issues.apache.org/jira/browse/IOTDB-2181

### CODE REVIEW

**Review by LebronAl — COMMENTED** [review]
LGTM~But we might need to talk a little bit more about whether we should return 0 or an error if the tagkey doesn't exist.
@qiaojialin cc

**Comment by qiaojialin** [comment]
Please update the UserGuide, add the behavior when the tag does not exist.

**Comment by cornmonster** [comment]
@qiaojialin Sorry for taking so long to update the PR. Please take another look at it.

**Review by LebronAl — APPROVED** [review]
LGTM

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
