### PR TITLE
[To rc/1.3.3] Combine CSV SQL TSfile data import/export script

### PR DESCRIPTION
**Pull request by 2b3c511**

### CODE REVIEW

**Comment by 2b3c511** [comment]
image
image
image
image
image

**Comment by CritasWang** [comment]
ImportTsFileRemotely.java

should be use params, not  `CommonDescriptor.getInstance().getConfig().getTimestampPrecision()`

**Comment by 2b3c511** [comment]
image

**Comment by 2b3c511** [comment]
image

**Review by CritasWang — APPROVED** [review]
LGTM

**Pull request merged**
