### PR TITLE
[IOTDB-1677] for rel/0.12, not generate file apache-iotdb-0.x.x-clien…

### PR DESCRIPTION
**Pull request by jamber001**
…t-cpp-linux-x86_64-bin.zip.sha512

### Content3 ...

<hr>

This PR has:
- [ ] been self-reviewed.
    - [ ] concurrent read
    - [ ] concurrent write
    - [ ] concurrent read and write 
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. 
- [ ] added or updated version, __license__, or notice information
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious 
  for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold 
  for code coverage.
- [ ] added integration tests.
- [ ] been tested in a test IoTDB cluster.

<hr>

### CODE REVIEW

**Review by HTHou — APPROVED** [review]
LGTM

**Review by HTHou — CHANGES_REQUESTED** [review]
Hi, you are committing into master branch actually...

**Comment by jamber001** [comment]
> Hi, you are committing into master branch actually...

sorry, I correct it soon

**Comment by HTHou** [comment]
> > Hi, you are committing into master branch actually...
> 
> sorry, I have just corrected it to rel/0.12

Eh, rebase needed...

**Comment by jamber001** [comment]
> > > Hi, you are committing into master branch actually...
> > 
> > 
> > sorry, I have just corrected it to rel/0.12
> 
> Eh, rebase needed...

en, I created 1 PR and will close this PR.

**Pull request closed without merging**
