### PR TITLE
[IOTDB-2283] REST: support metadata query

### PR DESCRIPTION
**Pull request by CloudWise-Lukemiao**
[IOTDB-2283]add metadata query

### CODE REVIEW

**Review by SilverNarcissus — APPROVED** [review]
Look good to me~

**Review by SteveYurongSu — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Please wait for my detailed review :D

**Review by SteveYurongSu — COMMENTED** [review]
I've made some refactors, PTAL. 

By the way, please add user doc.

**Review by SteveYurongSu — APPROVED** [review]
LGTM

**Pull request merged**
