### PR TITLE
[IOTDB-1159] set storage group exception message more clear

### PR DESCRIPTION
**Pull request by GLBB**
## Description
Require more clear error message for deleting and creating storage group
https://issues.apache.org/jira/browse/IOTDB-1159?jql=project%20%3D%20IOTDB%20AND%20issuetype%20%3D%20Bug%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

### CODE REVIEW

**Comment by wangchao316** [comment]
hi @GLBB , Thanks, this PR  affect other UT，you need deal...

**Comment by GLBB** [comment]
ok, today night i will solve it

**Comment by GLBB** [comment]
```
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.362 s <<< FAILURE! - in org.apache.iotdb.db.integration.IoTDBRemovePartitionIT
Error:  testRemoveAllPartition(org.apache.iotdb.db.integration.IoTDBRemovePartitionIT)  Time elapsed: 1.777 s  <<< FAILURE!
```
in local, i execute success, i don't known why ci execute failed

**Comment by HTHou** [comment]
> ```
> Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.362 s <<< FAILURE! - in org.apache.iotdb.db.integration.IoTDBRemovePartitionIT
> Error:  testRemoveAllPartition(org.apache.iotdb.db.integration.IoTDBRemovePartitionIT)  Time elapsed: 1.777 s  <<< FAILURE!
> ```
> 
> in my dev environment, i execute success, i don't known why ci execute failed

It's caused by other issue. You can ignore it in this PR.

**Review by qiaojialin — APPROVED** [review]

**Pull request merged**
