### PR TITLE
[PY-client] Unify setup.py and requirement.txt

### PR DESCRIPTION
**Pull request by HTHou**
## Description

https://github.com/apache/iotdb/issues/12591

### CODE REVIEW

**Comment by ycycse** [comment]
I find the version requirement in requirement.txt is 
`# Pandas Export
pandas>=1.3.5`
Should we unify these?

**Comment by ycycse** [comment]
> I find the version requirement in requirement.txt is `# Pandas Export pandas>=1.3.5` Should we unify these?

By the way, other requirements in requirement.txt are `# Pandas Export
pandas>=1.3.5
numpy>=1.21.4
thrift>=0.14.1
# SQLAlchemy Dialect
sqlalchemy == 1.3.20
sqlalchemy-utils == 0.36.8` which are not the same as the requirement in setup.py.

Generally speaking, the version in `setup.py` determines the specific version of dependencies that users will download when installing our package. The requirements.txt is typically the version that developers pay attention to. Although inconsistency will not affect usage, in order to unify the development and application environment, I think it is better to unify the two (or let requirements.txt include what setup specifies).

**Comment by HTHou** [comment]
> I find the version requirement in requirement.txt is `# Pandas Export pandas>=1.3.5` Should we unify these?

Yes, it makes sense. Fixed.

**Review by ycycse — APPROVED** [review]
LGTM~

**Comment by rmpinchback** [comment]
I don't have any opinions on the sqlalchemy version range because I haven't had reason know the v2 changes or how that could relate to the iotdb python client, but as for the pandas and numpy changes, that all looks good to me.  Thanks!

**Pull request merged**
