### PR TITLE
[IOTDB-2485] Fix bug that init mtree from snapshot won't update memTableMaxNum if …

### PR DESCRIPTION
**Pull request by chengjianyun**
memTableMaxNum won't update if mtree is initialized by snapshot file.

### CODE REVIEW

**Comment by qiaojialin** [comment]
Hi, please create an issue on jira and add a test

**Comment by chengjianyun** [comment]
> Hi, please create an issue on jira and add a test

jira isssue: https://issues.apache.org/jira/browse/IOTDB-2485

What do you mean _add a test_? Add a UT for the logic branch?

**Comment by HTHou** [comment]
> > Hi, please create an issue on jira and add a test
> 
> jira isssue: https://issues.apache.org/jira/browse/IOTDB-2485
> 
> What do you mean _add a test_? Add a UT for the logic branch?

Yes, adding a UT or IT. I think there should be some tests for mtree snapshot and we can enrich them.

**Comment by qiaojialin** [comment]
> > Hi, please create an issue on jira and add a test
> 
> jira isssue: https://issues.apache.org/jira/browse/IOTDB-2485
> 
> What do you mean _add a test_? Add a UT for the logic branch?

Yes~

**Comment by HTHou** [comment]
Ping.
Any update of this PR?

**Pull request closed without merging**
