### PR TITLE
[remove datanode] Procedure no longer acquires node lock

### PR DESCRIPTION
**Pull request by Pengzna**
as title.

### CODE REVIEW

**Review by HxpSerein — APPROVED** [review]
LGTM~

**Comment by wangchao316** [comment]
hi , why do no need node lock?   if have some addnodeprocedure perform now, our remove other node,   whether is effect?

**Comment by OneSizeFitsQuorum** [comment]
| hi , why do no need node lock? if have some addnodeprocedure perform now, our remove other node, whether is effect?

Hi, chao, this is because we have do check before executing RemoveDataNode Procedure(you could see the code in https://github.com/apache/iotdb/blob/master/iotdb-core/confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java#L619-L725).

Currently, only one removeDataNode task is allowed globally, so there is no need for additional concurrency control during procedure execution, otherwise it may cause some mutual blocking with pipe

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Comment by Pengzna** [comment]
> hi , why do no need node lock? if have some addnodeprocedure perform now, our remove other node, whether is effect?

hi, sorry for replying late, I just saw this message. As @OneSizeFitsQuorum  said, the upper layer of the procedure has been guaranteed to be safe, so the lock here is unnecessary because it may block other procedures.

**Pull request merged**
