### PR TITLE
[IOTDB-5393] Show Region creation time when execute show regions

### PR DESCRIPTION
**Pull request by CRZbulabula**
image

### CODE REVIEW

**Review by OneSizeFitsQuorum — COMMENTED** [review]
Do we need to consider time zones?

**Comment by CRZbulabula** [comment]
> Do we need to consider time zones?

Yes, I've added this feature~

**Review by OneSizeFitsQuorum — COMMENTED** [review]
Should we create a separate `createTime` column? Otherwise it seems ambiguous...

**Comment by CRZbulabula** [comment]
> Should we create a separate `createTime` column? Otherwise it seems ambiguous...

Created

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Review by xingtanzjr — APPROVED** [review]

**Pull request merged**
