### PR TITLE
[IOTDB-4074] Allocate SchemaRegion and DataRegion seperately

### PR DESCRIPTION
**Pull request by MiniSho**
Filter the specific consensusGroupType‘s allocatedRegions so that we can focus on the specified type of region allocation.

### CODE REVIEW

**Comment by MiniSho** [comment]
0b7e2fa7d594c076285ecb1cd640945

**Review by CRZbulabula — APPROVED** [review]
LGTM~Please add a screenshot that execute show datanode, which will display the number of SchemaRegion and the number of DataRegion in each DataNodes.

**Review by wangchao316 — APPROVED** [review]
LGTM

**Comment by MiniSho** [comment]
17833b981da5d5e7d5e7cfaa0217c5a

**Review by Beyyes — COMMENTED** [review]
What's the time complexity of removeIf.
How about filter consensusGroupType in getAllReplicaSets().

**Comment by MiniSho** [comment]
the time complexity is O(n²).
getAllReplicaSets() is used in many other places, so I think it's not a good idea to filter in it.

**Review by Beyyes — APPROVED** [review]
LGTM

**Pull request merged**
