### PR TITLE
[IOTDB-1240]support show node command in cluster version

### PR DESCRIPTION
**Pull request by yifuzhou**
## Description

show child nodes query is only supported in standalone version. In cluster version, when we use show child nodes query, it will only display local node's data.

### CODE REVIEW

**Comment by wangchao316** [comment]
good..
I have some small suggestion..
yifu ,you could add some UT or IT for your function..

**Review by wangchao316 — COMMENTED** [review]
good..
I have some small suggestion..
yifu ,you could add some UT or IT for your function..

**Review by neuyilan — APPROVED** [review]
Good Job!

**Comment by yifuzhou** [comment]
> good..
> I have some small suggestion..
> yifu ,you could add some UT or IT for your function..

Yes, I will add it later. Thanks~

**Review by wangchao316 — APPROVED** [review]
LGTM

**Review by LebronAl — APPROVED** [review]
LGTM~
BTW, could you please take a look at is there still some `show node command` not supported in cluster module? If so, you can fix it in next PR.

**Pull request merged**
