### PR TITLE
[To rel/0.12][IOTDB-1408]Statement with 'as' executes incorrectly in …

### PR DESCRIPTION
**Pull request by cmlmakahts**
One alias should only match with exactly one timeseries

【operations】
set storage group to root.auto1.wf02.wt02;
set storage group to root.auto1.wf01.wt02;
create timeseries root.auto1.wf01.wt02.status with datatype=boolean, encoding=plain
create timeseries root.auto1.wf01.wt02.temperature with datatype=float, encoding=plain, compression=snappy,max_point_number=3
create timeseries root.auto1.wf02.wt02.status with datatype=float, encoding=plain, compression=snappy,max_point_number=3
create timeseries root.auto1.wf02.wt02.temperature with datatype=float, encoding=plain, compression=snappy,max_point_number=3
insert into root.auto1.wf01.wt02(timestamp, status) values (now(), false);
insert into root.auto1.wf01.wt02(timestamp, temperature) values (now(), 66.7);
insert into root.auto1.wf02.wt02(timestamp, status) values (now(), 22.6);
insert into root.auto1.wf02.wt02(timestamp, temperature) values (now(), 33.7); 

SELECT status as speed FROM root.auto1.wf02.wt02,root.auto1.wf01.wt02
【result】
image

### CODE REVIEW

**Review by wangchao316 — APPROVED** [review]
LGTM

**Comment by Alima777** [comment]
Hi, there are some faults in the method `checkAndSetTsAlias()` 

For example:
IoTDB> SELECT status as speed, status as speed  FROM root.auto1.wf02.wt02
Msg: 411: Error occurred in query process: alias 'speed' can only be matched with one time series
which should not throw an exception.

I think we can just define **different time series cannot has the same alias**. 
Under this definition, you can define aliasMap like: alias(String) -> partitalPath
If one alias can be corresponding to different paths, we throw an exception.

**Review by Alima777 — CHANGES_REQUESTED** [review]
Please modify checkAndSetTsAlias() method

**Review by Alima777 — APPROVED** [review]
LGTM~

**Pull request merged**
