### PR TITLE
[IOTDB-3003]  data sync pipe recover bug & other issues

### PR DESCRIPTION
**Pull request by jamber001**
https://issues.apache.org/jira/browse/IOTDB-3003

### CODE REVIEW

**Comment by jamber001** [comment]
@Cpaulyz   Could you help review this code change?

**Review by Cpaulyz — APPROVED** [review]
LGTM

**Comment by jamber001** [comment]
@

> LGTM

thank you

**Comment by jamber001** [comment]
@HTHou  could you help merge this PR?     :-)

**Comment by jamber001** [comment]
@HTHou   thank you!

**Pull request merged**
