### PR TITLE
[To rel/1.1][IOTDB-6088] Load: Optimize the schema creation process & Avoid OOM and ratis createMultiTimeseriesPlan bufferSize too large 

### PR DESCRIPTION
**Pull request by MiniSho**
cherry-pick: https://github.com/apache/iotdb/pull/10715

### CODE REVIEW

**Comment by Cpaulyz** [comment]
IoTDBへの貢献に感謝します！おやすみなさい！

**Comment by SpriCoder** [comment]
Still working on the IoTDB community so late at night, thank you for your excellent contribution

**Comment by CRZbulabula** [comment]
Очень хорошо

**Review by SteveYurongSu — APPROVED** [review]

**Comment by SzyWilliam** [comment]
Bravo work! You are the very master of Load!

**Pull request merged**
