### PR TITLE
[IOTDB-5480] IoTConsensus sync lag may be negative under single copy

### PR DESCRIPTION
**Pull request by BUAAserein**
#### The threads of the LogDispatcher under single copy is empty, so safeIndex and searchIndex are the same value. The order of obtaining this value is related to the traversal order of the metricEntry in the PrometheusReporter, so it may be a negative value.  
Solution: Put two get directly into a function.
Subsequent improvements: Consider adding topological order to the traversal of metricEntry.
Please see details in [IOTDB-5480](https://issues.apache.org/jira/browse/IOTDB-5480).

### CODE REVIEW

**Review by OneSizeFitsQuorum — APPROVED** [review]
LGTM

**Review by SpriCoder — CHANGES_REQUESTED** [review]
Excellent Work!
Just one problem, Please update the en and zh doc at same time
en: docs/UserGuide/Monitor-Alert/Metric-Tool.md
zh: docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md

**Comment by BUAAserein** [comment]
> Excellent Work! Just one problem, Please update the en and zh doc at same time en: docs/UserGuide/Monitor-Alert/Metric-Tool.md zh: docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md

ok

**Review by SpriCoder — APPROVED** [review]
LGTM~

**Pull request merged**
