### PR TITLE
[ISSUE-3335] Fix the bug of start-cli.sh -e mode can't work with wildcard *

### PR DESCRIPTION
**Pull request by irvine0109**

### CODE REVIEW

**Comment by irvine0109** [comment]
#3336

**Comment by irvine0109** [comment]
image

**Comment by HTHou** [comment]
https://issues.apache.org/jira/browse/IOTDB-1274 
I think it's the same issue...

**Comment by HTHou** [comment]
Hi, did you try the Windows CLI?

**Comment by irvine0109** [comment]
> Hi, did you try the Windows CLI?

Windows CLI didn't have this bug. 
image

**Review by HTHou — APPROVED** [review]
LGTM

**Pull request merged**
