### PR TITLE
[IOTDB-1565]set system to readonly / writable Adaptive cluster

### PR DESCRIPTION
**Pull request by ijihang**
In #3771   we need the sql  Adaptive cluster

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, I have a question about this command in cluster mode. 
If I set System to readonly on the cli of one node, will other nodes change to readonly as well?

**Comment by ijihang** [comment]
> 您好，我对集群模式下的这个命令有疑问。
> 如果我在一个节点的 cli 上将 System 设置为只读，其他节点是否也会更改为只读？

yes,The cluster becomes read-only

**Review by neuyilan — APPROVED** [review]
LGTM

**Review by LebronAl — APPROVED** [review]
LGTM

**Review by LebronAl — APPROVED** [review]
I will merge this PR as failed test seems unrelated to this PR.
Don't forget to cherry-pick this PR to rel/0.12.
Thanks!

**Pull request merged**
