### PR TITLE
[IOTDB-2136] fix timeseries deletion issue

### PR DESCRIPTION
**Pull request by cornmonster**
See: https://issues.apache.org/jira/browse/IOTDB-2136

### CODE REVIEW

**Review by SteveYurongSu — COMMENTED** [review]
This issue is horrible...

We'd better add some tests to prevent this from happening again...

**Comment by SteveYurongSu** [comment]
Please take a look at the CI, it fails on https://github.com/apache/iotdb/runs/4503087034?check_suite_focus=true

image

**Comment by cornmonster** [comment]
> Please take a look at the CI, it fails on https://github.com/apache/iotdb/runs/4503087034?check_suite_focus=true
> 
> image

Sure

**Comment by cornmonster** [comment]
> This issue is horrible...
> 
> We'd better add some tests to prevent this from happening again...

The cluster IT can help us find flaws like this. But currently, there are too many failures, which makes it hard to tell if a new commit introduces new problems.

We are working on fixing the cluster issues. Once this job is done, the cluster IT results can be used to determine if a change should be merged or not.

**Review by MrQuansy — APPROVED** [review]

**Comment by MrQuansy** [comment]
LGTM

**Review by SteveYurongSu — APPROVED** [review]

**Review by LebronAl — APPROVED** [review]
LGTM

**Comment by LebronAl** [comment]
If convenient, please cherry-pick to branch 0.12. Thanks

**Pull request merged**
