### PR TITLE
Update pom.xml to fix security issue

### PR DESCRIPTION
**Pull request by HTHou**
## Description

https://github.com/apache/iotdb/security/dependabot

image

These dependences are not using in IoTDB currently, just remove them to fix the security warning.

### CODE REVIEW

**Review by chrisdutz — CHANGES_REQUESTED** [review]
Please also remove the comments in lines 1426-1430 as they referred to the removed dependency.

**Comment by chrisdutz** [comment]
I took the liberty to actually go through all dependencies and clean up the dependencyManagement as well as the properties.

**Comment by HTHou** [comment]
Thank you Chris, I saw you already updated this PR! 
So is it ready to merge?

**Comment by chrisdutz** [comment]
Yeah ... I first thought it needed that update but then I thought: I bet there's a lot more ... so I took the changes I had in my private fork of IoTDB (Wehre I migrated everything to Java 11 and Jakarta) ... turns out there was a lot more that could go.

**Pull request merged**
